In [22]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

training_set, test_set = mnist.load_data()

X_train, y_train = training_set
X_test, y_test = test_set

print(X_train.shape)

(60000, 28, 28)


In [23]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

print(X_train.shape)

(60000, 28, 28, 1)


In [24]:
X_train = X_train.astype(np.float) / 255.0  
X_test = X_test.astype(np.float) / 255.0

In [25]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

In [26]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)                7850      
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [28]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 3ms/step - loss: 0.7446 - accuracy: 0.8176 - val_loss: 0.4070 - val_accuracy: 0.8954
Epoch 2/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3890 - accuracy: 0.8961 - val_loss: 0.3334 - val_accuracy: 0.9115
Epoch 3/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3378 - accuracy: 0.9075 - val_loss: 0.3071 - val_accuracy: 0.9161
Epoch 4/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3142 - accuracy: 0.9136 - val_loss: 0.2942 - val_accuracy: 0.9181
Epoch 5/30
375/375 [==============================] - 1s 2ms/step - loss: 0.3002 - accuracy: 0.9167 - val_loss: 0.2841 - val_accuracy: 0.9220
Epoch 6/30
375/375 [==============================] - 1s 2ms/step - loss: 0.2907 - accuracy: 0.9194 - val_loss: 0.2804 - val_accuracy: 0.9221
Epoch 7/30
375/375 [==============================] - 1s 2ms/step - loss: 0.2834 - accuracy: 0.9203 - val_loss: 0.2755 - val_accuracy: 0.9242
Epoch 

In [29]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.98      1135
           2       0.93      0.90      0.91      1032
           3       0.91      0.91      0.91      1010
           4       0.95      0.92      0.94       982
           5       0.91      0.87      0.89       892
           6       0.95      0.95      0.95       958
           7       0.93      0.93      0.93      1028
           8       0.88      0.90      0.89       974
           9       0.91      0.92      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 964    0    1    2    0    5    5    2    1    0]
 [   0 1114    3    3    0    1    3    2    9    0]
 [   5    9  933   14    6    3   11    9   38    4]
 [   3    0   19  921    0   24    2   12   22    7]
 [   1    1    8    1  907   

# Sieć MLP

In [30]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_4 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_7 (Dense)              (None, 128)               8320      
_________________________________________________________________
dense_8 (Dense)              (None, 10)                1290      
Total params: 59,850
Trainable params: 59,850
Non-trainable params: 0
_________________________________________________________________


In [31]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [32]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 2s 3ms/step - loss: 0.4110 - accuracy: 0.8818 - val_loss: 0.2280 - val_accuracy: 0.9357
Epoch 2/30
375/375 [==============================] - 1s 3ms/step - loss: 0.1991 - accuracy: 0.9415 - val_loss: 0.1665 - val_accuracy: 0.9541
Epoch 3/30
375/375 [==============================] - 1s 3ms/step - loss: 0.1421 - accuracy: 0.9577 - val_loss: 0.1420 - val_accuracy: 0.9581
Epoch 4/30
375/375 [==============================] - 1s 3ms/step - loss: 0.1111 - accuracy: 0.9674 - val_loss: 0.1259 - val_accuracy: 0.9630
Epoch 5/30
375/375 [==============================] - 1s 3ms/step - loss: 0.0896 - accuracy: 0.9737 - val_loss: 0.1112 - val_accuracy: 0.9672
Epoch 6/30
375/375 [==============================] - 1s 3ms/step - loss: 0.0746 - accuracy: 0.9776 - val_loss: 0.1072 - val_accuracy: 0.9674
Epoch 7/30
375/375 [==============================] - 1s 3ms/step - loss: 0.0623 - accuracy: 0.9813 - val_loss: 0.1031 - val_accuracy: 0.9694
Epoch 

In [33]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.98      1.00      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.96      0.98      0.97      1010
           4       0.97      0.98      0.98       982
           5       0.97      0.95      0.96       892
           6       0.98      0.98      0.98       958
           7       0.97      0.96      0.97      1028
           8       0.98      0.97      0.97       974
           9       0.97      0.97      0.97      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 970    0    0    2    2    2    1    3    0    0]
 [   0 1130    2    0    0    1    1    1    0    0]
 [   5    1 1004    5    2    2    3    5    3    2]
 [   1    1    6  989    1    1    0    3    3    5]
 [   0    1    0    1  961   

# Sieć konwolucyjna

In [34]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 1600)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1600)              0         
_________________________________________________________________
dense_9 (Dense)              (None, 10)               

In [35]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [36]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 17s 44ms/step - loss: 0.3898 - accuracy: 0.8836 - val_loss: 0.0991 - val_accuracy: 0.9741
Epoch 2/30
375/375 [==============================] - 16s 43ms/step - loss: 0.1125 - accuracy: 0.9658 - val_loss: 0.0671 - val_accuracy: 0.9817
Epoch 3/30
375/375 [==============================] - 18s 49ms/step - loss: 0.0859 - accuracy: 0.9735 - val_loss: 0.0556 - val_accuracy: 0.9847
Epoch 4/30
375/375 [==============================] - 17s 45ms/step - loss: 0.0724 - accuracy: 0.9773 - val_loss: 0.0473 - val_accuracy: 0.9871
Epoch 5/30
375/375 [==============================] - 15s 41ms/step - loss: 0.0622 - accuracy: 0.9809 - val_loss: 0.0443 - val_accuracy: 0.9883
Epoch 6/30
375/375 [==============================] - 16s 41ms/step - loss: 0.0542 - accuracy: 0.9827 - val_loss: 0.0414 - val_accuracy: 0.9880
Epoch 7/30
375/375 [==============================] - 16s 42ms/step - loss: 0.0529 - accuracy: 0.9830 - val_loss: 0.0404 - val_accuracy:

In [37]:
y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       980
           1       0.99      1.00      1.00      1135
           2       0.99      1.00      0.99      1032
           3       0.99      1.00      0.99      1010
           4       0.99      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.98      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 977    0    1    0    0    0    0    1    1    0]
 [   0 1131    2    1    0    0    1    0    0    0]
 [   0    0 1027    0    1    0    0    4    0    0]
 [   0    0    0 1007    0    0    0    2    1    0]
 [   0    1    0    0  977   